List<Map<String, String>> _sampleData = [
    {'id': 'girl', 'image': 'assets/image0.jpg'},
    {'id': 'cat', 'image': 'assets/image1.jpg'},
    {'id': 'cat', 'image': 'assets/image2.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image3.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image4.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image5.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image6.jpg'},
    {'id': 'dog', 'image': 'assets/image7.jpg'},
    {'id': 'girl', 'image': 'assets/image8.jpg'},
    {'id': 'duck', 'image': 'assets/image9.jpg'},
    {'id': 'capybara', 'image': 'assets/image10.jpg'},
    {'id': 'cat', 'image': 'assets/image11.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image12.jpg'},
    {'id': 'girl', 'image': 'assets/image13.jpg'},
    {'id': 'cat', 'image': 'assets/image14.jpg'},
    {'id': 'cat', 'image': 'assets/image15.jpg'},
    {'id': 'cat', 'image': 'assets/image16.jpg'},
    {'id': 'cat', 'image': 'assets/image17.jpg'},
    {'id': 'profile', 'image': 'assets/image18.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image19.jpg'},
    {'id': 'cat', 'image': 'assets/image20.jpg'},
    {'id': 'capybara', 'image': 'assets/image21.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image22.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image23.jpg'},
    {'id': 'duck', 'image': 'assets/image24.jpg'},
    {'id': 'cat', 'image': 'assets/image25.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image26.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image27.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image28.jpg'},
    {'id': 'profile', 'image': 'assets/image29.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image30.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image31.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image32.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image33.jpg'},
    {'id': 'girl', 'image': 'assets/image34.jpg'},
    {'id': 'cat', 'image': 'assets/image35.jpg'},
    {'id': 'wallpaper', 'image': 'assets/image36.jpg'},
    {'id': 'girl', 'image': 'assets/image37.jpg'},
    {'id': 'girl', 'image': 'assets/image38.jpg'},
    {'id': '', 'image': 'assets/image39.jpg'},
  ];

List<Map<String, String>> get sampleData => _sampleData;